# Creación del grafo

In [1]:
import numpy as np
from timeit import default_timer as timer

In [2]:
# Número de vértices
N = 10

# Sucesores de cada vértice
grafo = np.zeros((10,10))

# Vecinos de 1
grafo[0,1] = 12; grafo[0,2] = 11; grafo[0,3] = 21

# Vecinos de 2
grafo[1,0] = 12; grafo[1,4] = 21; grafo[1,6] = 16

# Vecinos de 3
grafo[2,0] = 13; grafo[2,1] = 24; grafo[2,5] = 25; grafo[2,7] = 10

# Vecinos de 4
grafo[3,2] = 13; grafo[3,8] = 16

# Vecinos de 5
grafo[4,2] = 7; grafo[4,6] = 9; grafo[4,7] = 11

# Vecinos de 6
grafo[5,3] = 12; grafo[5,7] = 18; grafo[5,8] = 8

# Vecinos de 7
grafo[6,7] = 17; grafo[6,9] = 19

# Vecinos de 8
grafo[7,4] = 4; grafo[7,5] = 21; grafo[7,9] = 13

#### CAMBIAR A POSITIVO

# Vecinos de 9
grafo[8,7] = 17; grafo[8,9] = 21

# Para saber cuáles son los vecinos de i.
print(grafo)

[[ 0. 12. 11. 21.  0.  0.  0.  0.  0.  0.]
 [12.  0.  0.  0. 21.  0. 16.  0.  0.  0.]
 [13. 24.  0.  0.  0. 25.  0. 10.  0.  0.]
 [ 0.  0. 13.  0.  0.  0.  0.  0. 16.  0.]
 [ 0.  0.  7.  0.  0.  0.  9. 11.  0.  0.]
 [ 0.  0.  0. 12.  0.  0.  0. 18.  8.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 17.  0. 19.]
 [ 0.  0.  0.  0.  4. 21.  0.  0.  0. 13.]
 [ 0.  0.  0.  0.  0.  0.  0. 17.  0. 21.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### Probabilidades de transición

In [3]:
# Calcula p(j|i,a) donde a = (i,k)
def prob( i, j, a ):
    if len(a) != 2 or i >= 10 or j >= 10:
        print("Los valores no son correctos: \n i = ", i, 
              '\n j = ', j, '\n a = ', a)
    
    if i == 0: 
        if a == (0,1):
            if j == 1:
                return 0.7
            elif j == 2:
                return 0.1
            elif j == 3:
                return 0.2
        elif a == (0,2):
            if j == 1:
                return 0.2
            elif j == 2:
                return 0.5
            elif j == 3:
                return 0.3
        elif a == (0,3):
            if j == 1:
                return 0.1
            elif j == 2:
                return 0.1
            elif j == 3:
                return 0.8
            
    elif i == 1: 
        if a == (1,0):
            if j == 0:
                return 0.6
            elif j == 4:
                return 0.2
            elif j == 6:
                return 0.2
        elif a == (1,4):
            if j == 0:
                return 0.05
            elif j == 4:
                return 0.9
            elif j == 6:
                return 0.05
        elif a == (1,6):
            if j == 0:
                return 0.1
            elif j == 4:
                return 0.2
            elif j == 6:
                return 0.7
    
    elif i == 2: 
        if a == (2,0):
            if j == 0:
                return 0.6
            elif j == 1:
                return 0.1
            elif j == 5:
                return 0.2
            elif j == 7:
                return 0.1
        elif a == (2,1):
            if j == 0:
                return 0.2
            elif j == 1:
                return 0.4
            elif j == 5:
                return 0.2
            elif j == 7:
                return 0.2
        elif a == (2,5):
            if j == 0:
                return 0.3
            elif j == 1:
                return 0.1
            elif j == 5:
                return 0.4
            elif j == 7:
                return 0.2
        elif a == (2,7):
            if j == 0:
                return 0.3
            elif j == 1:
                return 0.1
            elif j == 5:
                return 0.2
            elif j == 7:
                return 0.4
    
    elif i == 3: 
        if a == (3,2):
            if j == 2:
                return 0.7
            elif j == 8:
                return 0.3
            else:
                return 0
        elif a == (3,8):
            if j == 2:
                return 0.5
            elif j == 8:
                return 0.5
    
    elif i == 4: 
        if a == (4,2):
            if j == 2:
                return 0.6
            elif j == 6:
                return 0.2
            elif j == 7:
                return 0.2
        elif a == (4,6):
            if j == 2:
                return 0.2
            elif j == 6:
                return 0.7
            elif j == 7:
                return 0.1
        elif a == (4,7):
            if j == 2:
                return 0.2
            elif j == 6:
                return 0.3
            elif j == 7:
                return 0.5
    
    elif i == 5: 
        if a == (5,3):
            if j == 3:
                return 0.2
            elif j == 7:
                return 0.5
            elif j == 8:
                return 0.3
        elif a == (5,7):
            if j == 3:
                return 0.2
            elif j == 7:
                return 0.5
            elif j == 8:
                return 0.3
        elif a == (5,8):
            if j == 3:
                return 0.3
            elif j == 7:
                return 0.3
            elif j == 8:
                return 0.4
    
    elif i == 6: 
        if a == (6,7):
            if j == 7:
                return 0.5
            elif j == 9:
                return 0.5
            else:
                return 0
        elif a == (6,9):
            if j == 7:
                return 0.3
            elif j == 9:
                return 0.7
    
    elif i == 7:
        if a == (7,4):
            if j == 4:
                return 0.6
            elif j == 5:
                return 0.2
            elif j == 9:
                return 0.2
        elif a == (7,5):
            if j == 4:
                return 0.2
            elif j == 5:
                return 0.5
            elif j == 9:
                return 0.3
        elif a == (7,9):
            if j == 4:
                return 0.3
            elif j == 5:
                return 0.3
            elif j == 9:
                return 0.4
    
    elif i == 8: 
        if a == (8,7):
            if j == 7:
                return 0.5
            elif j == 9:
                return 0.5
            else:
                return 0
        elif a == (8,9):
            if j == 7:
                return 0.1
            elif j == 9:
                return 0.9
        
    else:
        if j == 9:
            return 1
        else:
            return 0
    
    return 0
        
        

# Value iteration 

In [4]:
M = 10

In [5]:
def suma(s,a,v0):
    rta = 0
    for j in range(0,M):
        rta += prob(s,j,a)*v0[j]
    return rta


In [6]:
parar = False
M = 10
iteracion = 0
v0 = np.zeros(M)
eps = 0.01 # PREGUNTAR
    
start = timer()

while parar == False:
    iteracion += 1
    print( '\n #################### Iteración número ', iteracion, ' ####################\n' )
    vn = np.zeros(M)
    #Itero sobre los estados
    for s in range(0,M-1):        
        As = np.nonzero( grafo[s,:] != 0 )
        As = np.ndarray.tolist(As[0])
        
        valores = np.zeros(len(As))
        
        for i in range(0,len(As)):
            valores[i] = (grafo[s,As[i]] + suma(s,(s,As[i]),v0))
        
        vn[s] = np.min(valores)
        
    #Condición de parada
    if np.linalg.norm( np.subtract( vn,v0 ) ) < eps:
        parar = True

    v0 = vn
    
# Fin del ciclo. Calculo la política
d = np.zeros(M)

for s in range(0,M-1):        
    As = np.nonzero( grafo[s,:] != 0 )
    As = np.ndarray.tolist(As[0])

    valores = np.zeros(len(As))

    for a in range(0,len(As)):
        valores[a] = grafo[s,As[a]] + suma(s,(s,As[a]),v0)

    d[s] = As[np.argmin(valores)]
d[M-1] = M-1
print(d)

end = timer()
print(end - start) 



 #################### Iteración número  1  ####################


 #################### Iteración número  2  ####################


 #################### Iteración número  3  ####################


 #################### Iteración número  4  ####################


 #################### Iteración número  5  ####################


 #################### Iteración número  6  ####################


 #################### Iteración número  7  ####################


 #################### Iteración número  8  ####################


 #################### Iteración número  9  ####################


 #################### Iteración número  10  ####################


 #################### Iteración número  11  ####################


 #################### Iteración número  12  ####################


 #################### Iteración número  13  ####################


 #################### Iteración número  14  ####################


 #################### Iteración número  15  ####################


 ##

# Policy iteration

In [7]:
def calculo_Pdn_y_rdn(d):
    P = np.identity(M)
    for i in range(0,M):
        P[i,i] = 1
    r = np.zeros(M)
    
    for s in range(0,M-1):
        accion = d[s]
        
        r[s] = grafo[s,int(accion)]
        
        As = np.nonzero( grafo[s,:]!= 0 )
        As = np.ndarray.tolist( As[0] )
        
        for t in As:
            P[s,t] = P[s,t] - prob( s,t,(s,accion) )
    
    return (P,r)

In [8]:
start = timer()

d0 = np.zeros(M)
for s in range(0,M-1):
    d0[s] = np.ndarray.tolist(np.nonzero( grafo[s,:] > 0 )[0])[0]
#Condición de parada
parar = False
iteraciones = 1

while( parar == False ):
    print('################# Iteración número: ', iteraciones, '#################\n')
    dn = np.zeros(M)
    
    #Calculamos qué es P_dn y r_dn 
    (P_dn,r_dn) = calculo_Pdn_y_rdn(d0)
                           
    #Quiero resolver el sistema de ecuacones (P_dn)v = r_dn.
    v_n = np.linalg.solve(P_dn,r_dn)
    
    #Cálculo de d_n+1
    #Iteramos sobre todos los estados posibles 
    
    ###########################################
    for s in range(0,M-1):
        #Itero sobre las posibles acciones
        As = np.nonzero( grafo[s,:]!= 0 )
        As = np.ndarray.tolist(As[0])
        
        valores = np.zeros(len(As))
        
        for a in range(0,len(As)):
            valores[a] = grafo[s,As[a]] + suma(s,(s,As[a]),v0)

        valorMinimo = np.min(valores)
        
        if( d0[s] == valorMinimo ):
            dn[s] = d0[s] 
        else:
            dn[s] = As[np.argmin(valores)]
    
    dn[M-1] = M-1
    #Condición de parada:
    parar = (dn==d0).all()
    d0 = dn
    iteraciones += 1
    #Fin del ciclo.
print(dn)
end = timer()
print(end - start)

################# Iteración número:  1 #################

################# Iteración número:  2 #################

[1. 6. 7. 8. 6. 8. 9. 9. 9. 9.]
0.058425200000002064


# Montecarlo para RL 

In [20]:
from numpy.random import choice

In [30]:
def simulacion():
    nodoActual = 0
    camino = []
    acciones = []
    probabilidades = []
    
    final = False
    while final == False:
        As = np.nonzero( grafo[nodoActual,:]!= 0 )
        As = np.ndarray.tolist(As[0])
        
        accion = np.random.choice(As)
        probs = np.zeros(len(As))
        for a in range(0,len(As)):
            probs[a] = prob(nodoActual, As[a], (nodoActual,accion))
        
        draw = choice(range(0,len(As)), 1, p=probs)
        probabilidades.append(probs[draw[0]])
        camino.append(As[draw[0]])
        acciones.append(accion)
        
        nodoActual = camino[-1]
        
        if nodoActual == M-1:
            final = True
            
    return (camino, probabilidades, acciones)

In [106]:
probabilidades = [[]]*M

for i in range(0,M):
    As = np.nonzero( grafo[i,:]!= 0 )
    As = np.ndarray.tolist(As[0])
    probabilidades[i] = dict.fromkeys([str(i)+str(a) for a in As],[])
    
    for a in As:        
        newdic = dict.fromkeys([str(i)+str(a)+str(j) for j in As],[])
        
        probabilidades[i][str(i)+str(a)] = newdic
    
probabilidades

[{'01': {'011': [], '012': [], '013': []},
  '02': {'021': [], '022': [], '023': []},
  '03': {'031': [], '032': [], '033': []}},
 {'10': {'100': [], '104': [], '106': []},
  '14': {'140': [], '144': [], '146': []},
  '16': {'160': [], '164': [], '166': []}},
 {'20': {'200': [], '201': [], '205': [], '207': []},
  '21': {'210': [], '211': [], '215': [], '217': []},
  '25': {'250': [], '251': [], '255': [], '257': []},
  '27': {'270': [], '271': [], '275': [], '277': []}},
 {'32': {'322': [], '328': []}, '38': {'382': [], '388': []}},
 {'42': {'422': [], '426': [], '427': []},
  '46': {'462': [], '466': [], '467': []},
  '47': {'472': [], '476': [], '477': []}},
 {'53': {'533': [], '537': [], '538': []},
  '57': {'573': [], '577': [], '578': []},
  '58': {'583': [], '587': [], '588': []}},
 {'67': {'677': [], '679': []}, '69': {'697': [], '699': []}},
 {'74': {'744': [], '745': [], '749': []},
  '75': {'754': [], '755': [], '759': []},
  '79': {'794': [], '795': [], '799': []}},
 {'87':

In [79]:
start = timer()

d0 = np.zeros(M)
for s in range(0,M-1):
    d0[s] = np.ndarray.tolist(np.nonzero( grafo[s,:] > 0 )[0])[0]
#Condición de parada
parar = False
iteraciones = 1

while( parar == False ):
    print('################# Iteración número: ', iteraciones, '#################\n')
    dn = np.zeros(M)
  
    #Policy evaluation
    visitados = np.zeros(M)

    #Calculo v_dn^m
    m = 0
    vd0 = np.zeros(M)

    costos = np.full((M,M^3),-1)

    while m < M^3:
        vdn = np.zeros(M)
        
        (camino, prob, acciones) = simulacion()
                
        visitados[0] += 1
        probabilidades[0][acciones[0]][camino[1]].append(prob[i+1])

        suma = 0
        for i in range(0,len(camino)):
            
            visitados[camino[len(camino)-i-1]] += 1 
            if i > 0:
                suma += grafo[camino[len(camino)-i-2],camino[len(camino)-i-1]]
            else:
                suma += grafo[0,camino[len(camino)-i-1]]
            
            if i != len(camino)-1:
                probabilidades[camino[i]][acciones[i]][camino[i+1]].append(prob[i+1])

            costos[camino[len(camino)-i]] = suma
            
        if costos[:,]
    

            
            
                
                
            
        
    
    
print(dn)
end = timer()
print(end - start)

SyntaxError: invalid syntax (<ipython-input-79-f87d2a88bbeb>, line 45)

array((), dtype=[])